Update system packages

diff --git a/scripts/.local/bin/convert_supernotes_to_pdf b/scripts/.local/bin/convert_supernotes_to_pdf
--- a/scripts/.local/bin/convert_supernotes_to_pdf
+++ b/scripts/.local/bin/convert_supernotes_to_pdf
@@ -2,14 +2,20 @@
 
 set -o pipefail
 
+echo "$(date) Starting conversion..."
+
 /Users/pritesh/.local/bin/supernote-toolkit \
   -input /Users/pritesh/Backups/supernote/Note/ \
   -output /Users/pritesh/Backups/supernote/PDFs
 
-if [ $NOTIFY ]; then
-  if [ $? -ne 0 ]; then
+if [ $? -ne 0 ]; then
+  echo "$(date) Conversion failed!"
+  if [ $NOTIFY ]; then
     $NOTIFY "Supernotes conversion failed! Please check logs."
-  else
+  fi
+else
+  echo "$(date) Conversion successful!"
+  if [ $NOTIFY ]; then
     $NOTIFY "Supernotes converted successfully!"
   fi
 fi
diff --git a/scripts/.local/bin/sync_sandisk b/scripts/.local/bin/sync_sandisk
--- a/scripts/.local/bin/sync_sandisk
+++ b/scripts/.local/bin/sync_sandisk
@@ -2,12 +2,13 @@
 
 set -o pipefail
 
-if [ $NOTIFY ]; then $NOTIFY "Syncing Sandisk"; fi
-
 if [[ ! -e /Volumes/Sandisk ]]; then
-  echo "Sandisk not mounted"
+  echo "$(date) Sandisk not mounted!"
   exit
 fi
+
+echo "$(date) Starting sandisk sync..."
+if [ $NOTIFY ]; then $NOTIFY "Syncing Sandisk"; fi
 
 rsync \
   --archive \
@@ -24,10 +25,14 @@ rsync \
   $HOME/.dotfiles \
   /Volumes/Sandisk && diskutil unmount Sandisk
 
-if [ $NOTIFY ]; then
-  if [ $? -ne 0 ]; then
+if [ $? -ne 0 ]; then
+  echo "$(date) Sandisk sync failed!"
+  if [ $NOTIFY ]; then
     $NOTIFY "Sandisk synced failed! Please check logs."
-  else
+  fi
+else
+  echo "$(date) Sandisk sync successful!"
+  if [ $NOTIFY ]; then
     $NOTIFY "Sandisk synced successfully!"
   fi
 fi
